<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

<h3 style="color:purple">Sample problem of predicting home price in monroe, new jersey (USA)</h3>

Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms,  5 year old**

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

C:\Users\Lenovo\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Data Preprocessing: Fill NA values with median value of a column**

In [3]:
df.bedrooms.median()

4.0

In [5]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [9]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [10]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [11]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

<h3>Exercise<h3>

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**


In [67]:
df=pd.read_csv('hiring.csv')

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [62]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [87]:
# pip install word2number

In [85]:
from word2number import w2n

def convert_word_to_number(value):
    try:
        return w2n.word_to_num(value)  # Chuyển đổi chuỗi thành số
    except ValueError:
        return value  # Nếu không chuyển đổi được, giữ nguyên giá trị




In [86]:
convert_word_to_number('five')

5


In [93]:
df['experience'] = df['experience'].apply(convert_word_to_number)

In [94]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [95]:
df['salary']=df['salary($)']

In [108]:
n_df = df.drop('salary($)',axis='columns')

In [109]:
# remove null value
new_df = n_df.dropna()

In [110]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 2 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  5 non-null      float64
 1   test_score(out of 10)       5 non-null      float64
 2   interview_score(out of 10)  5 non-null      int64  
 3   salary                      5 non-null      int64  
dtypes: float64(2), int64(2)
memory usage: 200.0 bytes


In [111]:
reg = linear_model.LinearRegression()
reg.fit(new_df.drop('salary',axis='columns'),new_df['salary'])

LinearRegression()

<h3>Answer<h3>

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [112]:
print('Nhap kinh nghiem lam viec: ')
x = float(input())
print('Nhap test score: ')
y = float(input())
print('Nhap interview score: ')
z = float(input())

vecto = (x,y,z)

salary = reg.intercept_ + sum(vecto[i] * reg.coef_[i] for i in range(len(vecto)))
print('Luong cua ban la: ',salary)

Nhap kinh nghiem lam viec: 
2
Nhap test score: 
9
Nhap interview score: 
6
Luong cua ban la:  56365.37746374116


Ket qua khac nhau do cach xu li missing values khac nhau. Toi quyet dinh xoa cac gia tri null thay vi thay the chung bang mean hay median.

53713.86 and 93747.79